# Generated by Django 3.2.8 on 2022-08-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 18, 22, 28, 48909)),
        ),
    ]
